# Generated by Django 5.2.8 on 2025-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_sellernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
