# Generated by Django 5.2.8 on 2025-11-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_product_rating'),
        ('Seller', '0003_alter_product_rating'),
    ]

    operations = [
    ]
